### ISSUE TITLE
鼠标hover时变成小手

### ISSUE THREAD

**Issue by fncheng** [fncheng/CSS#1]
[MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/cursor)
```css
&:hover {
  cursor: pointer;
}
```
