### ISSUE TITLE
浏览器缩放的自适应方案

### ISSUE THREAD

**Issue by fncheng** [fncheng/CSS#16]
当浏览器缩放或者是系统的设置中的显示比例缩放，导致页面比例不对（通常是过大）时，该如何做一个自适应解决方案

一般来说，浏览器放大了，那么我就将对应页面缩小即可

页面的缩放，有两种实现方案

**1. zoom属性**

这是一个较旧的 CSS 属性，主要用于缩放元素的内容。当应用 zoom 时，它会缩放整个元素（包括文本、图片、边框等）并影响元素的布局和大小。zoom 只对块级元素有效，且其行为在不同浏览器之间存在兼容性差异。

zoom会影响元素的实际尺寸（即它的 width、height 等属性），并且可能会改变页面的布局。这可能会导致页面的重排和其他元素的位置变化。

**2. transform: scale**

这是一个现代的 CSS 属性，应用于元素的变换（平移、旋转、缩放等）。scale 会根据指定的比例缩放元素的外观，但不改变元素的实际尺寸。与 zoom 不同，scale 不会影响布局或其他元素的相对位置，因此不会造成页面的重新流动。

以下是transform: scale实现的缩小
```css
@media screen and (max-width: 1152px) {
  #app {
    transform: scale(0.8);
    transform-origin: top left;
    width: 125%;
    height: 125%;
  }
}
```

这里设置width: 125%，是为了补偿偿缩放操作对元素尺寸的影响，从而确保缩放后的元素不被裁切或者出现视觉上的不一致。

这样，当浏览器放大125%时，通过上述操作让页面缩小0.8倍，这样就能够保持和100%时同样的展示效果。从而不让页面过大。
