### ISSUE TITLE
CSS background实现渐变文字的效果

### ISSUE THREAD

**Issue by fncheng** [fncheng/CSS#17]
## 通过background实现渐变文字效果

```css
.gradient-text {
  font-size: 48px;
  font-weight: bold;
  background: linear-gradient(to right, #4caf50, #9c27b0, #f44336); /* 渐变色 */
  -webkit-background-clip: text; /* 背景裁剪为文字形状 */
  -webkit-text-fill-color: transparent; /* 文字填充设为透明，显示背景 */
}
```
