### ISSUE TITLE
div填充满屏幕

### ISSUE THREAD

**Issue by fncheng** [fncheng/CSS#3]
让一个div充满屏幕

### 1. 定位position
```css
 css中position有五种属性：　
      static:默认值，没有定位
      absolute:绝对定位，相对于父级元素进行定位
      relative:相对定位 
      fixed:固定定位,相对于浏览器窗口进行定位
      inherit:从父元素继承定位信息
```
除了默认值static和inherit之外，添加其他三种都可以实现窗口自适应。

代码如下：
```css
/* magin和padding = 0 不然会有滚动条现象 */
* {
        margin: 0;
        padding: 0;
      }
      div {
        width: 100%;
        height: 100%;
        position: absolute;
        background-color: antiquewhite;
      }
```

### 2. height: 100%
代码如下：
```css
* {
        margin: 0;
        padding: 0;
      }
      html,
      body {
        height: 100%;
      }
      div {
        height: 100%;
        background-color: antiquewhite;
      }
```
⚠️需要注意的是：height：100%需要先定义html和body的高度为height：100%才生效的

### 3. height: 100vh
```css
* {
        margin: 0;
        padding: 0;
      }
      div {
        height: 100vh;
        background-color: antiquewhite;
      }
```

**Comment by fncheng** [comment]
### [vw布局](https://jelly.jd.com/article/6006b1055b6c6a01506c8801)

**Comment by fncheng** [comment]
对于第二种方法 height: 100%

```css
/* 如果我们只设置body的高度 */
body {
  height: 100%;
}
```

这样是不行的，因为子盒子的高度继承自父盒子，那么问题来了，**html元素的高度是从哪来的呢，或者说继承自谁呢？**
猜测：

  1. window
  2. document.documentElement

这两个高度是一样的

### [window](https://developer.mozilla.org/zh-CN/docs/Web/API/Window)

window 对象表示一个包含DOM文档的窗口，其 document 属性指向窗口中载入的 DOM文档 。

window.innerHeight 实际上是浏览器可视区域的高度

### [document](https://developer.mozilla.org/zh-CN/docs/Web/API/Document)

Document 接口表示任何在浏览器中载入的网页，并作为网页内容的入口，也就是DOM 树。DOM 树包含了像 \<body> 、\<table> 这样的元素，以及大量其他元素。
